# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: systemconfig.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='systemconfig.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12systemconfig.proto\"\x8a\x01\n\x0cSystemconfig\x12\x19\n\x11SecurityParameter\x18\x01 \x01(\x05\x12\"\n\x1aMaximumTransactionInterval\x18\x02 \x01(\x05\x12\x1e\n\x16MaximumTransactionRate\x18\x03 \x01(\x05\x12\x1b\n\x13PunishmentThreshold\x18\x04 \x01(\x05\x62\x06proto3')
)




_SYSTEMCONFIG = _descriptor.Descriptor(
  name='Systemconfig',
  full_name='Systemconfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='SecurityParameter', full_name='Systemconfig.SecurityParameter', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='MaximumTransactionInterval', full_name='Systemconfig.MaximumTransactionInterval', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='MaximumTransactionRate', full_name='Systemconfig.MaximumTransactionRate', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='PunishmentThreshold', full_name='Systemconfig.PunishmentThreshold', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=161,
)

DESCRIPTOR.message_types_by_name['Systemconfig'] = _SYSTEMCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Systemconfig = _reflection.GeneratedProtocolMessageType('Systemconfig', (_message.Message,), dict(
  DESCRIPTOR = _SYSTEMCONFIG,
  __module__ = 'systemconfig_pb2'
  # @@protoc_insertion_point(class_scope:Systemconfig)
  ))
_sym_db.RegisterMessage(Systemconfig)


# @@protoc_insertion_point(module_scope)
