/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "transaction.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(TransactionHeader, TransactionHeader, AUTO)


PB_BIND(Transaction, Transaction, AUTO)


PB_BIND(TransactionList, TransactionList, AUTO)



