# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: properties.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='properties.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10properties.proto\"q\n\nProperties\x12\x17\n\x0f\x41ttestationType\x18\x01 \x01(\t\x12\x18\n\x10ReliabilityScore\x18\x02 \x01(\x02\x12\x14\n\x0cTimeFunction\x18\x03 \x01(\t\x12\x0c\n\x04xmin\x18\x04 \x01(\x02\x12\x0c\n\x04xmax\x18\x05 \x01(\x02\"1\n\x0ePropertiesList\x12\x1f\n\nProperties\x18\x01 \x03(\x0b\x32\x0b.Propertiesb\x06proto3')
)




_PROPERTIES = _descriptor.Descriptor(
  name='Properties',
  full_name='Properties',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='AttestationType', full_name='Properties.AttestationType', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ReliabilityScore', full_name='Properties.ReliabilityScore', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='TimeFunction', full_name='Properties.TimeFunction', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='xmin', full_name='Properties.xmin', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='xmax', full_name='Properties.xmax', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=133,
)


_PROPERTIESLIST = _descriptor.Descriptor(
  name='PropertiesList',
  full_name='PropertiesList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Properties', full_name='PropertiesList.Properties', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=184,
)

_PROPERTIESLIST.fields_by_name['Properties'].message_type = _PROPERTIES
DESCRIPTOR.message_types_by_name['Properties'] = _PROPERTIES
DESCRIPTOR.message_types_by_name['PropertiesList'] = _PROPERTIESLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Properties = _reflection.GeneratedProtocolMessageType('Properties', (_message.Message,), dict(
  DESCRIPTOR = _PROPERTIES,
  __module__ = 'properties_pb2'
  # @@protoc_insertion_point(class_scope:Properties)
  ))
_sym_db.RegisterMessage(Properties)

PropertiesList = _reflection.GeneratedProtocolMessageType('PropertiesList', (_message.Message,), dict(
  DESCRIPTOR = _PROPERTIESLIST,
  __module__ = 'properties_pb2'
  # @@protoc_insertion_point(class_scope:PropertiesList)
  ))
_sym_db.RegisterMessage(PropertiesList)


# @@protoc_insertion_point(module_scope)
