/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: batch.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "batch.pb-c.h"
void   batch_header__init
                     (BatchHeader         *message)
{
  static const BatchHeader init_value = BATCH_HEADER__INIT;
  *message = init_value;
}
size_t batch_header__get_packed_size
                     (const BatchHeader *message)
{
  assert(message->base.descriptor == &batch_header__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t batch_header__pack
                     (const BatchHeader *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &batch_header__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t batch_header__pack_to_buffer
                     (const BatchHeader *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &batch_header__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BatchHeader *
       batch_header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BatchHeader *)
     protobuf_c_message_unpack (&batch_header__descriptor,
                                allocator, len, data);
}
void   batch_header__free_unpacked
                     (BatchHeader *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &batch_header__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   batch__init
                     (Batch         *message)
{
  static const Batch init_value = BATCH__INIT;
  *message = init_value;
}
size_t batch__get_packed_size
                     (const Batch *message)
{
  assert(message->base.descriptor == &batch__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t batch__pack
                     (const Batch *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &batch__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t batch__pack_to_buffer
                     (const Batch *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &batch__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Batch *
       batch__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Batch *)
     protobuf_c_message_unpack (&batch__descriptor,
                                allocator, len, data);
}
void   batch__free_unpacked
                     (Batch *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &batch__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   batch_list__init
                     (BatchList         *message)
{
  static const BatchList init_value = BATCH_LIST__INIT;
  *message = init_value;
}
size_t batch_list__get_packed_size
                     (const BatchList *message)
{
  assert(message->base.descriptor == &batch_list__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t batch_list__pack
                     (const BatchList *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &batch_list__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t batch_list__pack_to_buffer
                     (const BatchList *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &batch_list__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BatchList *
       batch_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BatchList *)
     protobuf_c_message_unpack (&batch_list__descriptor,
                                allocator, len, data);
}
void   batch_list__free_unpacked
                     (BatchList *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &batch_list__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor batch_header__field_descriptors[2] =
{
  {
    "signer_public_key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(BatchHeader, signer_public_key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "transaction_ids",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(BatchHeader, n_transaction_ids),
    offsetof(BatchHeader, transaction_ids),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned batch_header__field_indices_by_name[] = {
  0,   /* field[0] = signer_public_key */
  1,   /* field[1] = transaction_ids */
};
static const ProtobufCIntRange batch_header__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor batch_header__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "BatchHeader",
  "BatchHeader",
  "BatchHeader",
  "",
  sizeof(BatchHeader),
  2,
  batch_header__field_descriptors,
  batch_header__field_indices_by_name,
  1,  batch_header__number_ranges,
  (ProtobufCMessageInit) batch_header__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor batch__field_descriptors[4] =
{
  {
    "header",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Batch, header),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "header_signature",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Batch, header_signature),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "transactions",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Batch, n_transactions),
    offsetof(Batch, transactions),
    &transaction__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "trace",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Batch, trace),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned batch__field_indices_by_name[] = {
  0,   /* field[0] = header */
  1,   /* field[1] = header_signature */
  3,   /* field[3] = trace */
  2,   /* field[2] = transactions */
};
static const ProtobufCIntRange batch__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor batch__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Batch",
  "Batch",
  "Batch",
  "",
  sizeof(Batch),
  4,
  batch__field_descriptors,
  batch__field_indices_by_name,
  1,  batch__number_ranges,
  (ProtobufCMessageInit) batch__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor batch_list__field_descriptors[1] =
{
  {
    "batches",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(BatchList, n_batches),
    offsetof(BatchList, batches),
    &batch__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned batch_list__field_indices_by_name[] = {
  0,   /* field[0] = batches */
};
static const ProtobufCIntRange batch_list__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor batch_list__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "BatchList",
  "BatchList",
  "BatchList",
  "",
  sizeof(BatchList),
  1,
  batch_list__field_descriptors,
  batch_list__field_indices_by_name,
  1,  batch_list__number_ranges,
  (ProtobufCMessageInit) batch_list__init,
  NULL,NULL,NULL    /* reserved[123] */
};
