/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: check_request.proto */

#ifndef PROTOBUF_C_check_5frequest_2eproto__INCLUDED
#define PROTOBUF_C_check_5frequest_2eproto__INCLUDED

#include "protobuf-c.h"

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Checkrequest Checkrequest;


/* --- enums --- */


/* --- messages --- */

struct  Checkrequest
{
  ProtobufCMessage base;
  char *deviceid;
};
#define CHECKREQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&checkrequest__descriptor) \
    , (char *)protobuf_c_empty_string }


/* Checkrequest methods */
void   checkrequest__init
                     (Checkrequest         *message);
size_t checkrequest__get_packed_size
                     (const Checkrequest   *message);
size_t checkrequest__pack
                     (const Checkrequest   *message,
                      uint8_t             *out);
size_t checkrequest__pack_to_buffer
                     (const Checkrequest   *message,
                      ProtobufCBuffer     *buffer);
Checkrequest *
       checkrequest__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   checkrequest__free_unpacked
                     (Checkrequest *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Checkrequest_Closure)
                 (const Checkrequest *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor checkrequest__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_check_5frequest_2eproto__INCLUDED */
