/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: evidence.proto */

#ifndef PROTOBUF_C_evidence_2eproto__INCLUDED
#define PROTOBUF_C_evidence_2eproto__INCLUDED

#include "protobuf-c.h"

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Evidence Evidence;


/* --- enums --- */


/* --- messages --- */

struct  Evidence
{
  ProtobufCMessage base;
  char *proveridentity;
  char *blockid;
  char *measurement;
};
#define EVIDENCE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&evidence__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/* Evidence methods */
void   evidence__init
                     (Evidence         *message);
size_t evidence__get_packed_size
                     (const Evidence   *message);
size_t evidence__pack
                     (const Evidence   *message,
                      uint8_t             *out);
size_t evidence__pack_to_buffer
                     (const Evidence   *message,
                      ProtobufCBuffer     *buffer);
Evidence *
       evidence__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   evidence__free_unpacked
                     (Evidence *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Evidence_Closure)
                 (const Evidence *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor evidence__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_evidence_2eproto__INCLUDED */
