/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: trust_query.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "trust_query.pb-c.h"
void   trust_query__init
                     (TrustQuery         *message)
{
  static const TrustQuery init_value = TRUST_QUERY__INIT;
  *message = init_value;
}
size_t trust_query__get_packed_size
                     (const TrustQuery *message)
{
  assert(message->base.descriptor == &trust_query__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t trust_query__pack
                     (const TrustQuery *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &trust_query__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t trust_query__pack_to_buffer
                     (const TrustQuery *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &trust_query__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TrustQuery *
       trust_query__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TrustQuery *)
     protobuf_c_message_unpack (&trust_query__descriptor,
                                allocator, len, data);
}
void   trust_query__free_unpacked
                     (TrustQuery *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &trust_query__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor trust_query__field_descriptors[2] =
{
  {
    "Trustor",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TrustQuery, trustor),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Trustee",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TrustQuery, trustee),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned trust_query__field_indices_by_name[] = {
  1,   /* field[1] = Trustee */
  0,   /* field[0] = Trustor */
};
static const ProtobufCIntRange trust_query__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor trust_query__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TrustQuery",
  "TrustQuery",
  "TrustQuery",
  "",
  sizeof(TrustQuery),
  2,
  trust_query__field_descriptors,
  trust_query__field_indices_by_name,
  1,  trust_query__number_ranges,
  (ProtobufCMessageInit) trust_query__init,
  NULL,NULL,NULL    /* reserved[123] */
};
