/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: trust_query.proto */

#ifndef PROTOBUF_C_trust_5fquery_2eproto__INCLUDED
#define PROTOBUF_C_trust_5fquery_2eproto__INCLUDED

#include "protobuf-c.h"

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct TrustQuery TrustQuery;


/* --- enums --- */


/* --- messages --- */

struct  TrustQuery
{
  ProtobufCMessage base;
  char *trustor;
  char *trustee;
};
#define TRUST_QUERY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&trust_query__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/* TrustQuery methods */
void   trust_query__init
                     (TrustQuery         *message);
size_t trust_query__get_packed_size
                     (const TrustQuery   *message);
size_t trust_query__pack
                     (const TrustQuery   *message,
                      uint8_t             *out);
size_t trust_query__pack_to_buffer
                     (const TrustQuery   *message,
                      ProtobufCBuffer     *buffer);
TrustQuery *
       trust_query__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   trust_query__free_unpacked
                     (TrustQuery *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*TrustQuery_Closure)
                 (const TrustQuery *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor trust_query__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_trust_5fquery_2eproto__INCLUDED */
