# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: check_request.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='check_request.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13\x63heck_request.proto\" \n\x0c\x43heckrequest\x12\x10\n\x08\x44\x65viceID\x18\x01 \x01(\tb\x06proto3')
)




_CHECKREQUEST = _descriptor.Descriptor(
  name='Checkrequest',
  full_name='Checkrequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='DeviceID', full_name='Checkrequest.DeviceID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=55,
)

DESCRIPTOR.message_types_by_name['Checkrequest'] = _CHECKREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Checkrequest = _reflection.GeneratedProtocolMessageType('Checkrequest', (_message.Message,), dict(
  DESCRIPTOR = _CHECKREQUEST,
  __module__ = 'check_request_pb2'
  # @@protoc_insertion_point(class_scope:Checkrequest)
  ))
_sym_db.RegisterMessage(Checkrequest)


# @@protoc_insertion_point(module_scope)
